# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-25 17:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bloodbanks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BloodReq',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('btype', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=200)),
                ('hospname', models.CharField(max_length=50)),
                ('Area', models.CharField(max_length=50)),
            ],
        ),
        migrations.RenameModel(
            old_name='User',
            new_name='Donor',
        ),
        migrations.AddField(
            model_name='bloodbank',
            name='abnunit',
            field=models.CharField(default='0', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bloodbank',
            name='abpunit',
            field=models.CharField(default='0', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bloodbank',
            name='anunit',
            field=models.CharField(default='0', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bloodbank',
            name='apunit',
            field=models.CharField(default='0', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bloodbank',
            name='bnunit',
            field=models.CharField(default='0', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bloodbank',
            name='bpunit',
            field=models.CharField(default='0', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bloodbank',
            name='onunit',
            field=models.CharField(default='0', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bloodbank',
            name='opunit',
            field=models.CharField(default='0', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bloodreq',
            name='donor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bloodbanks.Donor'),
        ),
    ]
