# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-26 07:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloodbanks', '0002_auto_20170425_2249'),
    ]

    operations = [
        migrations.AddField(
            model_name='donor',
            name='btype',
            field=models.CharField(default='Ap', max_length=20),
            preserve_default=False,
        ),
    ]
