# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-26 07:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloodbanks', '0003_donor_btype'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloodreq',
            name='units',
            field=models.CharField(default='2', max_length=50),
            preserve_default=False,
        ),
    ]
